### ISSUE TITLE
Feature request: show the QR code for the secret key

### ISSUE THREAD

**Issue by acrostich** [twofas/2fas-ios#35] opened 2023-08-23 18:30 UTC
It is sometimes useful to import the 2FA token in another app. 2FAS has the option to copy the secret key for a token which is great. It would be even better if there was also the option to display the associated QR code.

**Comment by FrankyFFV** [comment] 2023-09-15 06:21
> It is sometimes useful to import the 2FA token in another app. 2FAS has the option to copy the secret key for a token which is great. It would be even better if there was also the option to display the associated QR code.

+1

Please @2fas-com, add below "Secret Key" an option to "Show QR code". Very useful for easily scan with another phone.

**Comment by OddHouseGames** [comment] 2023-11-24 03:32
Would love this feature to, for creating a 2nd copy or sharing with a family member.

**Comment by joeri-juramento** [comment] 2024-02-06 14:35
ℹ️ #28

**Comment by KobeW50** [comment] 2024-02-22 22:21
Closing as a duplicate of #28

**Closed** 2024-02-22 22:21 UTC
Labels: enhancement
